# Generated by Django 4.2.7 on 2024-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("promotional_discount", models.PositiveIntegerField(default=0)),
                ("shipping_fee", models.PositiveIntegerField(default=0)),
                ("total_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("Ongoing", "Ongoing"),
                            ("Upcomming", "Upcomming"),
                        ],
                        default="Ongoing",
                        max_length=64,
                    ),
                ),
                (
                    "carts",
                    models.ManyToManyField(related_name="checkouts", to="shop.cart"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
